### ISSUE TITLE
Origin of `modboot.img`?

### ISSUE THREAD

**Issue by daveloyall** [x29a/nec_terrain_root#1]
Hi, @x29a!  What is the origin of `modboot.img`?  How was it constructed?

I'd like to reproduce the process here.

Thanks, cheers,
--Dave L.

**Comment by x29a** [comment]
Hi Dave, [modboot.img](https://github.com/x29a/nec_terrain_root/blob/master/terroot/app/src/main/assets/modboot.img) was built by @alex-kas and is provided over at [his repository](https://github.com/alex-kas/nec_terrain/tree/master/boot). He described [his findings](https://forum.xda-developers.com/showpost.php?p=61016468&postcount=121) (basically the whole thread is gold, see [XDA-Developer forum links specifically for the NEC Terrain](https://github.com/x29a/nec_terrain_root/blob/master/README.md) for more threads on this topic) on xda-dev. Some tools to handle Android bootimg files are provided at [xda-dev](https://forum.xda-developers.com/showthread.php?t=2319018). 

All i tried to do was pack his work into a simple to use android app for rooting directly on device. There has been some renaming and new versions of files which were only party incorporated, which might add to the confusion (diff is your friend).

Hope this helps, it has been quite a while since working on nec terrain...

Just out of curiousity, may i ask where the sudden interest comes from? Great to see some NEC Terrain love in 2017 :)

**Comment by daveloyall** [comment]
x29a, these are currently for sale, new.  They cost more now than they did in 2015...

Just like the other NEC Terrain fans, I like the hardware keyboard and rugged design.

I've read the whole 40 page thread and a few others.  What an adventure!

Too bad the GPL source released by NEC is 1. no longer available and 2. didn't include drivers for the phone's hardware.  I think they were supposed to include those... IANAL, but don't kernel modules fall under the GPL?

Since the keyboard lacks a CTRL key, I guess I'll have to figure out how the stock kernel talks to the keyboard and write some driver that does the same task.

**Comment by daveloyall** [comment]
There's a project that asks the question "Why can't I use a mobile device for ten years?"  It's here: [postmarketOS](https://ollieparanoid.github.io/post/postmarketOS/).

If you want to use a device for so long, it better be rugged. :)
